Updates made by Running Child
shuanaongithub/dpyjs-python pull request #5
Opened 2021-02-27 10:44 UTC by AzeAstro

I added #Start and #End tags where I edited or added commands.

I added in bot.py:
1)Load <cog name>(Users in admins_list only)
2)Reload <cog name>(Users in admins_list only)
3)Unload <cog name>(Users in admins_list only)

Added in cogs:
1)Do and Make: These two are kinda fun commands. like: `py/make me sandwich` and  it returns random answer.

2)OSU Command combinations(in Misc.py) Returns user info according to given options
usage:
py/osu <option:required> <username:required> <mode:optional>
option can be best/recent/user
mode can be standart/taiko/ctb/mania

3)Needed things:
1)Avatar: Ig it doesn't need explaination
1)Userinfo: Returns user info in embed
2)Serverinfo:  Returns server info in embed
3)Vote: Makes vote embed for 2 options. usage:
py/vote <countdown:optional int> <arg1,arg2>

4)quote: Returns quote
5)Anilist: Returns detailed info about anime/manga. Usage:
py/<anilist or aniinfo> <anime/manga(one of them)> <name>
Note about why I didn't use anilist:
Anilist has API Token which is expiring after 1 year but anilist is modern + uses graphiql + required no token + (and ofc I coudln't work with MyAnimeList's API xD )

4)Memes
1)Meme: Returns meme from r/Memes
2)Animeme: Returns animeme from r/Animemes
3)Cursed: Returns cursed comment pic from r/cursedcursedcomments
r/Cursed required Reddit API and it would make it slow + creepy. so ig r/cursedcursedcomments is best desicion for now.

5)Status:
1)Status: Changes status and saves it(for applying status on restart,add it in commands.Bot part)
usage:
py/status <status>

## Summary

## Checklist

- [x] If code changes were made then they have been tested.
- [x] This PR's changes are cogs related.
  - [x] This PR adds a command.
  - [ ] This PR removes a command.
  - [ ] This PR modifies an existing command's code.
- [ ] This PR is **not** a code change (e.g. documentation, README, ...)

2021-02-27 11:04 UTC, vierofernando requested changes
good pr, but there are some parts of the code that are better changed before merging

2021-02-27 11:04 UTC, vierofernando commented on cogs/misc.py
> +					async with cs.get(f"https://osu.ppy.sh/api/get_user?u={user}&k=8cc26d81bf2e174deea7b8d8a504279c07ba9998") as r:
put the API key as an environment variable instead, e.g `os.environ['OSU_TOKEN']`

2021-02-27 11:30 UTC, AzeAstro commented on cogs/misc.py
> +					async with cs.get(f"https://osu.ppy.sh/api/get_user?u={user}&k=8cc26d81bf2e174deea7b8d8a504279c07ba9998") as r:
no matters really.

2021-02-27 11:30 UTC, AzeAstro commented on cogs/memes.py
> +                x=random.choice(list_posts)
but what will change?

2021-02-27 11:30 UTC, AzeAstro commented on cogs/do_make.py
> +    @commands.command(aliases=["do","Do"])
I didn't saw it in commands.Bot :sweat_smile:

2021-02-27 11:30 UTC, AzeAstro commented on bot.py
> +async def load_cmd(ctx, extension):
right :sweat_smile:

2021-02-27 11:39 UTC, vierofernando commented on cogs/memes.py
> +                x=random.choice(list_posts)
replace
```
list_posts=range(0,25)
x=random.choice(list_posts) 
```
with
```
x = random.randint(0, 25)
```

2021-02-27 11:39 UTC, vierofernando commented on cogs/misc.py
> +					async with cs.get(f"https://osu.ppy.sh/api/get_user?u={user}&k=8cc26d81bf2e174deea7b8d8a504279c07ba9998") as r:
alright.

2021-03-01 01:21 UTC, shuanaongithub commented
Thanks.

2021-03-01 01:22 UTC, merged